#version: '3.8'

services:
  web:
    image: php:8.0.28-apache
    container_name: mi-apache
    ports:
      - "8000:80"
    volumes:
      - ./src/var/www:/var/www/html
    networks:
      - app-network
    command: /bin/bash -c "apt-get update && apt-get install -y nano && docker-php-ext-install pdo pdo_mysql && a2enmod rewrite && apache2-foreground"

  db:
    image: mysql:5.7
    container_name: mi-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mi_db
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contraseña
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mi-phpmyadmin
    environment:
      PMA_HOST: mi-mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
